### ISSUE TITLE
Contribute the web page to Zephyr upstream?

### ISSUE THREAD

**Issue by kartben** [finikorg/webusb-serial#3]
Hi @finikorg! Would it make sense to host the HTML page directly on the official Zephyr docs? I see no reason why this should not work, right? Thanks!

**Comment by finikorg** [comment]
Do you mean this: https://github.com/finikorg/webusb-sample/blob/master/index.html

**Comment by kartben** [comment]
Yep! would be great to have it directly served from docs.zephyrproject.org rather than having the webusb sample link to an external Github Pages

**Comment by finikorg** [comment]
So do you mean copy that index.html to the zephyr sample folder ?

**Comment by larsgk** [comment]
If only one file (no imports/fetches), it can just be opened as a file in the browser (and still be considered "secure" and run)

**Comment by finikorg** [comment]
Can I point browser to something like: https://zephyrproject.github.io/zephyr/tree/main/samples/subsys/usb/webusb ?

**Comment by larsgk** [comment]
> Can I point browser to something like: https://zephyrproject.github.io/zephyr/tree/main/samples/subsys/usb/webusb ?

It just needs to be served over https - or run locally (file on disk or served on localhost). If you have the source anyway (to build the sample) - if just a single html file, it can be opened and run in a local browser

**Comment by kartben** [comment]
Something like this https://github.com/zephyrproject-rtos/zephyr/compare/main...kartben:zephyr:webusb_app

This would then let people browse the demo directly from https://docs.zephyrproject.org/latest/samples/subsys/usb/webusb/demo.html while also having the merit to put the HTML demo code directly in the repo for folks to be able to more easily re-use for their own needs.
If you have a chance and agree it's a good idea, could you finish this up? As this is your code, it would be better to have the PR coming from you :) I think the only thing missing would be to update the existing github pages links to be `` :doc:`demo` `` instead, and maybe to also have a `:file:  ... html `  link somewhere to point people to the source HTML if they want to dig into the code.

<img width="1052" alt="image" src="https://github.com/finikorg/webusb-sample/assets/128251/41484254-42b5-4854-9087-b349c813688c">

**Comment by finikorg** [comment]
We need to get this WebUSB demo app out of samples TOC, otherwise it is working.

**Comment by finikorg** [comment]
fixed
